on:
  push:
    branches:
      - "**"

jobs:
  validate-terraform:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - id: tf-version
        run: echo "version=$(grep '^terraform ' .tool-versions | awk '{print $2}')" >> "$GITHUB_OUTPUT"
        working-directory: .

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ steps.tf-version.outputs.version }}

      - run: terraform init -backend=false

      - run: terraform validate
